<section class="about-founder section" aria-labelledby="about-founder-title">
    <div class="container"><div class="section-heading"><p class="section-heading__eyebrow">Câu chuyện <strong>sáng lập</strong></p><h2 id="about-founder-title">THÔNG ĐIỆP TỪ FOUNDER MS. THU HẰNG</h2></div>
        <div class="about-founder__card"><img src="<?php echo m_english_about_image('founder-portrait.png'); ?>" alt="Founder Ms. Thu Hằng tương tác với học sinh" width="683" height="577" loading="lazy"><div class="about-founder__card-copy"><h3>Ms. Thu Hằng</h3><p>Founder M-English với hơn 22+ năm kinh nghiệm trực tiếp giảng dạy, nghiên cứu, phát triển chương trình và cố vấn Anh ngữ mầm non.</p></div></div>
    </div>
    <div class="about-founder__story"><div class="container about-founder__story-rows">
        <div class="about-founder__story-row"><p>M-English ra đời từ trăn trở làm sao để mỗi giờ học tiếng Anh của trẻ mầm non không phải là áp lực thi phô, đọc vẹt hay những bảng từ vựng khô khan. Chúng tôi tin rằng ngôn ngữ phải được bắt đầu từ cảm xúc, từ những giai điệu ngân vang và những câu chuyện chạm đến trái tim.</p><img class="about-founder__mascot about-founder__mascot--vegetables" src="<?php echo m_english_about_image('founder-vegetable-mascots.png'); ?>" alt="" width="683" height="359" loading="lazy"></div>
        <div class="about-founder__story-row about-founder__story-row--reverse"><img class="about-founder__mascot about-founder__mascot--story" src="<?php echo m_english_about_image('founder-story-mascot.png'); ?>" alt="" width="527" height="399" loading="lazy"><p>Suốt hơn 22 năm đồng hành cùng giáo dục mầm non, tôi đã chứng kiến hàng ngàn đứa trẻ bật âm tự nhiên, tự tin biểu diễn trên sân khấu lớp học khi được tiếp cận đúng phương pháp. M-English được đóng gói chuẩn hóa không chỉ để truyền cảm hứng cho trẻ, mà còn để đồng hành cùng các nhà trường, giải phóng 80% áp lực soạn bài cho giáo viên, giúp mọi giáo viên mầm non làm chủ lớp học Anh ngữ trơn tru và giàu năng lượng nhất.</p></div>
    </div></div>
</section>
