<section class="home-experts section"><div class="container"><div class="section-heading"><p class="section-heading__eyebrow">Bảo chứng <strong>chuyên môn</strong></p><h2>ĐÁNH GIÁ TỪ 5 CHUYÊN GIA GIÁO DỤC</h2></div><div class="home-experts__grid">
<?php $experts = [
    ['TS. Nguyễn Thị Thu Huyền', 'Tiến sĩ Giáo dục học, Đại học East Anglia (Anh Quốc) | 20 năm kinh nghiệm giảng dạy, quản lý và cố vấn giáo dục toàn quốc | Nguyên Giảng viên Tâm lý học - ĐH SP HCM | Nguyên Giám đốc chuyên môn, Tổng Hiệu trưởng tại BCIS, VFIS, PATHWAY...', 'Vui vẻ, dễ chịu và ứng dụng cao. Hằng không nói quá nhiều. Hằng làm mẫu rồi học viên hình dung và thực hành, sáng tạo thêm. Hằng là một nghệ sĩ không ngừng sáng tạo. Hằng đang làm thứ mà Hằng giỏi nhất và đam mê nhất: Dạy tiếng Anh cho trẻ mầm non bằng những cách thức vui vẻ, hiệu quả nhất. Dưới con mắt chuyên nghiên cứu về tâm lý học giáo dục của mình thì chương trình đào tạo và sản phẩm này là research-based – có nền tảng khoa học của việc học và tâm lý học phát triển.'],
    ['TS. Nguyễn Thúy Hồng Vân', 'Director of INTESOL Vietnam / TESOL Master Trainer (Đại diện INTESOL Worldwide UK tại VN) | Managing Director, Veducation Global | Lecturer tại RMIT University Vietnam | Nguyên CEO ITD Academy & Director I-HUTECH.', 'Một ngày hoà mình vào thế giới tuổi thơ với khoá đào tạo giáo viên Tiếng Anh mầm non của M-English. Rất nhiều tips và techniques dạy trẻ mầm non được chia sẻ trong khoá huấn luyện giáo viên mầm non. Đón chờ một hợp tác mới giữa Veducation và M-English: Tiếng Anh Mầm Non trong thời gian sắp tới. Thực sự tuyệt vời!'],
    ['ThS. Đoàn Thị Thuận', 'Giám đốc vận hành GDMN Bee Garden | 30 năm kinh nghiệm ngành GDMN.', 'Chương trình không chỉ dựa trên tâm lý học lứa tuổi, mà còn xuất phát từ sự thấu hiểu tinh tế về trẻ em... Năng lượng tích cực khiến việc dạy và học trở nên đầy ý nghĩa.'],
    ['Cô Nguyễn Hồng Minh', 'Education Programs Manager · Microsoft Vietnam.', 'Tôi tin một người giàu năng lượng, đam mê và sáng tạo như cô Hằng đã dành tâm huyết và đầu tư, thì sản phẩm 100% Made in Vietnam này sẽ ra gì và này nọ chứ chẳng đùa đâu!'],
    ['TS. Đinh Thị Thu Hằng', 'Tiến sĩ GDMN · ĐH Hiroshima (Nhật Bản) | Giảng viên Khoa GDMN - ĐH Sư phạm Đà Nẵng.', 'Giàu tri thức, giàu cảm xúc và giàu kết nối. Khóa học mở ra không gian học tập chan hòa cảm hứng – nơi giáo viên tìm thấy sự đồng hành và niềm vui thật sự trong nghề.'],
]; foreach ($experts as $expert) : ?>
<article class="home-experts__item"><div class="home-experts__avatar" aria-hidden="true"></div><h3><?php echo esc_html($expert[0]); ?></h3><p class="home-experts__role"><?php echo esc_html($expert[1]); ?></p><blockquote>“<?php echo esc_html($expert[2]); ?>”</blockquote></article>
<?php endforeach; ?></div></div></section>
